# Generated by Django 5.0.2 on 2024-03-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.IntegerField()),
                ('piso', models.CharField(max_length=2)),
                ('descripcion', models.CharField(max_length=100)),
                ('caracteristicas', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=15)),
                ('tipo_habitacion', models.CharField(max_length=20)),
            ],
        ),
    ]
