# Generated by Django 5.0.3 on 2024-04-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumo',
        ),
    ]
