# Generated by Django 5.0.2 on 2024-03-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
