# Generated by Django 5.0.3 on 2024-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_monto_ingresado_alter_factura_cambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
