# Generated by Django 5.0.3 on 2024-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dias_hospedados',
            field=models.IntegerField(default=0),
        ),
    ]
