# Generated by Django 5.0.3 on 2024-04-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_dias_hospedados'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='consumos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
